### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by niklas-heer** [niklas-heer/speed-comparison#54]
It should only run if something is changed in the relevant files (`src/*`, `Earthfile`, ...) not if documentation or assets are updated.

**Comment by Akaame** [comment]
```yaml
on:
  push:
    paths-ignore:
      - 'assets'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    branches:
      - master
      - next
  pull_request_review:
    types: [submitted]
  pull_request:
    types:
      - labeled
 ```
 
 Should do it, I suppose. What else would you add to the list of ignored paths?
